apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: create-dir
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: create-dir
  template:
    metadata:
      labels:
        name: create-dir
    spec:
      containers:
      - name: create-dir
        image: 962116418130.dkr.ecr.ap-southeast-1.amazonaws.com/vendor1-busybox:latest
        command: ['sh', '-c', 'mkdir -p /mnt/disks/vol1 /mnt/disks/vol2 && chmod 777 /mnt/disks/vol1 /mnt/disks/vol2 && echo "Directories /mnt/disks/vol1 and /mnt/disks/vol2 created successfully" && while true; do sleep 60; done']        volumeMounts:
        - name: host-mount
          mountPath: /mnt/disks
      volumes:
      - name: host-mount
        hostPath:
          path: /mnt/disks
          type: DirectoryOrCreate