apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: create-dir
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: create-dir
  template:
    metadata:
      labels:
        name: create-dir
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-10-9-48-56.ap-southeast-1.compute.internal
      containers:
      - name: create-dir
        image: busybox
        command: ['sh', '-c', 'mkdir -p /mnt/disks/vol1 && chmod 777 /mnt/disks/vol1 && while true; do sleep 3600; done']
        volumeMounts:
        - name: host-mount
          mountPath: /mnt/disks
      volumes:
      - name: host-mount
        hostPath:
          path: /mnt/disks
          type: DirectoryOrCreate