apiVersion: v1
kind: Pod
metadata:
  name: sleep-pod
  namespace: kafka
spec:
  containers:
  - name: sleep-container
    image: 962116418130.dkr.ecr.ap-southeast-1.amazonaws.com/vendor1-confluent-init-container:2.2.0-1
    command: ["sleep", "infinity"]
    securityContext:
      runAsUser: 0
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"