apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-operator-full-access
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: airflow-full-access
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]