apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-operator-full-access-binding
subjects:
- kind: ServiceAccount
  name: emr-containers-sa-spark
  namespace: emr-spark-operator
roleRef:
  kind: ClusterRole
  name: spark-operator-full-access
  apiGroup: rbac.authorization.k8s.io