apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
      - name: kafka-ui
        image: 962116418130.dkr.ecr.ap-southeast-1.amazonaws.com/vendor1-kafka-ui:latest
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_CLUSTERS_0_NAME
          value: local
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          value: 'b-1.vpbpocdevextmskcl.h7bk9y.c5.kafka.ap-southeast-1.amazonaws.com:9092,b-2.vpbpocdevextmskcl.h7bk9y.c5.kafka.ap-southeast-1.amazonaws.com:9092'
        - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
          value: http://ext-schema-registry.aws.poc-06.vpbank.dev:8081
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: /proxy/absolute/9000/
        - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME
          value: first
        - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS
          value: http://s3.kafka.svc.cluster.local:8083
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"