---
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: s3
  namespace: kafka
  annotations:
    platform.confluent.io/connector-wget-extra-args: " --no-check-certificate"
spec:
  keyConverterType: io.confluent.connect.avro.AvroConverter
  valueConverterType: io.confluent.connect.avro.AvroConverter
  replicas: 1
  image:
    application: 962116418130.dkr.ecr.ap-southeast-1.amazonaws.com/vendor1-cp-server-connect:7.0.2
    init: 962116418130.dkr.ecr.ap-southeast-1.amazonaws.com/vendor1-confluent-init-container:2.2.0-1
  build:
    type: onDemand
    onDemand:
      plugins:
        locationType: url
        url:
          - name: kafka-connect-s3
            archivePath: https://raw.githubusercontent.com/hnhonnguyen/eks-data-platform/8d8166dc6c3a711aaea725c6eef7023ebcd66a22/confluentinc-kafka-connect-s3-10.5.13.zip
            checksum: d362bebfc33cb834949e6b930b20129a02e1b81143fecb8a56a5e12b05693f10349ab0f8233a00f3200185614d7c9f9d7737f80495354a6cc95f779591661167
  dependencies:
    kafka:
      bootstrapEndpoint: 'b-1.vpbpocdevextmskcl.h7bk9y.c5.kafka.ap-southeast-1.amazonaws.com:9092,b-2.vpbpocdevextmskcl.h7bk9y.c5.kafka.ap-southeast-1.amazonaws.com:9092'
      # authentication:
      #   type: plain
      #   jaasConfig:
      #     secretRef: ccloud-credentials
      # tls:
      #   enabled: true
      #   ignoreTrustStoreConfig: true 
    schemaRegistry:
      url: http://ext-schema-registry.aws.poc-06.vpbank.dev:8081
  #     authentication:
  #       type: basic
  #       basic:
  #         secretRef: ccloud-sr-credentials
  # mountedSecrets:
  # - secretRef: mysql-credential