---
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: S3
  namespace: kafka
spec:
  keyConverterType: io.confluent.connect.avro.AvroConverter
  valueConverterType: io.confluent.connect.avro.AvroConverter
  replicas: 1
  image:
    application: 962116418130.dkr.ecr.ap-southeast-1.amazonaws.com/vendor1-cp-server-connect:7.0.2
    init: 962116418130.dkr.ecr.ap-southeast-1.amazonaws.com/vendor1-confluent-init-container:2.2.0-1
  build:
    type: onDemand
    onDemand:
      plugins:
        confluentHub: []
        url: []
          # - name: kafka-connect-s3
          #   archivePath: https://raw.githubusercontent.com/confluentinc/confluent-kubernetes-examples/master/hybrid/ccloud-JDBC-mysql/confluentinc-kafka-connect-jdbc-10.2.5.zip
          #   checksum: 9d033fabac89ec0b35a97246f7ca3a36800bcb402ccfbd76adebd4c4c9ca6e7d6a044a9162383a18f99400893581b55a87b9fe89e35276507e9a3fb6cff3fda0
  dependencies:
    kafka:
      bootstrapEndpoint: 'b-1.vpbpocdevextmskcl.h7bk9y.c5.kafka.ap-southeast-1.amazonaws.com:9092,b-2.vpbpocdevextmskcl.h7bk9y.c5.kafka.ap-southeast-1.amazonaws.com:9092'
      # authentication:
      #   type: plain
      #   jaasConfig:
      #     secretRef: ccloud-credentials
      # tls:
      #   enabled: true
      #   ignoreTrustStoreConfig: true 
    schemaRegistry:
      url: http://ext-schema-registry.aws.poc-06.vpbank.dev:8081
  #     authentication:
  #       type: basic
  #       basic:
  #         secretRef: ccloud-sr-credentials
  # mountedSecrets:
  # - secretRef: mysql-credential