apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
    name: s3
    namespace: kafka
spec:
    replicas: 1
    image:
        application: 962116418130.dkr.ecr.ap-southeast-1.amazonaws.com/vendor1-cp-server-connect:7.0.1
        # init: 962116418130.dkr.ecr.ap-southeast-1.amazonaws.com/vendor1-confluent-init-container:2.2.0-1
    podTemplate:
        resources:
            requests:
                cpu: 1000m
                memory: 512Mi
        probe:
            liveness:
                periodSeconds: 10
                failureThreshold: 5
                timeoutSeconds: 30
                initialDelaySeconds: 100
            readiness:
                periodSeconds: 10
                failureThreshold: 5
                timeoutSeconds: 30
                initialDelaySeconds: 100
        podSecurityContext:
            fsGroup: 1000
            runAsUser: 1000
            runAsNonRoot: true
    build:
        type: onDemand
        onDemand:
            plugins: {}
    dependencies:
        kafka:
            bootstrapEndpoint: "b-1.vpbpocdevextmskcl.h7bk9y.c5.kafka.ap-southeast-1.amazonaws.com:9092,b-2.vpbpocdevextmskcl.h7bk9y.c5.kafka.ap-southeast-1.amazonaws.com:9092"
            # authentication:
            #     type: plain
            #     jaasConfig:
            #         secretRef: ccloud-credentials
            # tls:
            #     enabled: true
            #     ignoreTrustStoreConfig: true
        schemaRegistry:
            url: http://ext-schema-registry.aws.poc-06.vpbank.dev:8081
            #  authentication:
            #    type: basic
            #    basic:
            #      secretRef: ccloud-sr-credentials
