---
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: s3
  namespace: kafka
spec:
  keyConverterType: io.confluent.connect.avro.AvroConverter
  valueConverterType: io.confluent.connect.avro.AvroConverter
  replicas: 1
  image:
    application: 962116418130.dkr.ecr.ap-southeast-1.amazonaws.com/vendor1-cp-server-connect:7.0.2
    init: 962116418130.dkr.ecr.ap-southeast-1.amazonaws.com/vendor1-confluent-init-container:2.2.0-1
  build:
    type: onDemand
    onDemand:
      plugins:
        locationType: url
        url:
          - name: kafka-connect-s3
            archivePath: https://vendor1-poc-emr-20240725114624169500000001.s3.ap-southeast-1.amazonaws.com/kafkaconnect/confluentinc-kafka-connect-s3-10.5.13.zip?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEFQaDmFwLXNvdXRoZWFzdC0xIkgwRgIhAKy00o82ne2OtMP7eblyTYrDzKMEZulel%2F61d6SR1CnQAiEAi7%2BQlQykc1su8Ixy6jOcIyHwjD0MrDfOJq7zBLtxe3cqhQMIPRAAGgw5NjIxMTY0MTgxMzAiDIHeanuXLJ1CmVNkqSriArStXnivnuDM3U9VzrUHYTyhl6dvX3CGlvHzm%2BZRCLnh4alCTEeuMXsgicPl2I8c7YZlRWqY54xmw9FmO21xejEIeYbx98Xb0l5foi9shv8Bx1ouWD42LUruCV3aNeoXGQmlXKTE%2BHoEZcvKf2BqOAQ91MMrg2z6pYw%2FbvbxcuER4o5w6BIDrcmX2eCwSn1sskcb6a9cqYeI2WxwNIrN%2B%2FIz46EGEq9ibbnuVMt7BG52N2hP6aT4BKWtXMtuTKlXJ4PD2q1F1Exq1M%2Fqygy7iefBeYRTUk7IDUHrqL4nzS%2FNEeLwhuqlTKEmD6%2F9OzziHhr%2F5VQnNkAey6gVgTJYjo98i1ZFZKhwQ%2FMlCZfDtPZT%2Bp9feo4kI5GoXbkf3qXhWcZIlfjlnOOhYGQKwjPk%2BYEhZTKxswpv93%2BxP5ueFXpMYn3EbxNidV%2F4ZZh0nVcpdPl%2FzmK%2BL5s9O%2BzYgeFG5AKMbzDvoaG1BjqyAlVRzfujmkQ47lq0yOMfRWSw%2FYq4Fm8zDE0VgJcR4N1qhaUHjKs5LkriQV4gor5CKnm9PNzowNcze9of3yPkLw4wAcuRHeKcBp%2BBxOSOki48j%2FuG%2F4vJqubPBn4DYcSJoMi7RN2eLRi9dBn8gyUHAnGw5RQtqA3r%2F6uJ1CZP7XqhQourKdz%2BVD4PR%2FbXJrWi%2BstBQf514IqR%2FnugunQK1ljDeJbCdTT%2FLfCg2nTvS%2B5KIoT0jh1DPEnylFE%2FO3IPwBpqC6o5D7FeLRSs4x%2BAVPzc0FpljRZZI%2FL0nXwkG0faaHGO1ph8MDDEIkKO5vMQNao%2FolsDVvT6boqGNbDOzFDgVI1N3WTf3ASjxM4viij0K%2Fg6q9WFD%2F1gGkKWwXn6hDC5yestdKzPTc9O5vouBbzzaA%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240730T042609Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIA6AAU3PJJJTLBFJCM%2F20240730%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Signature=b07c93b0625d352ac6454dd53b01c732865d06c2f7ad933093dbfc07e2f74c15
            checksum: d362bebfc33cb834949e6b930b20129a02e1b81143fecb8a56a5e12b05693f10349ab0f8233a00f3200185614d7c9f9d7737f80495354a6cc95f779591661167
  dependencies:
    kafka:
      bootstrapEndpoint: 'b-1.vpbpocdevextmskcl.h7bk9y.c5.kafka.ap-southeast-1.amazonaws.com:9092,b-2.vpbpocdevextmskcl.h7bk9y.c5.kafka.ap-southeast-1.amazonaws.com:9092'
      # authentication:
      #   type: plain
      #   jaasConfig:
      #     secretRef: ccloud-credentials
      # tls:
      #   enabled: true
      #   ignoreTrustStoreConfig: true 
    schemaRegistry:
      url: http://ext-schema-registry.aws.poc-06.vpbank.dev:8081
  #     authentication:
  #       type: basic
  #       basic:
  #         secretRef: ccloud-sr-credentials
  # mountedSecrets:
  # - secretRef: mysql-credential